services:
  # Redis for Celery tasks
  redis:
    image: redis:6
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      zookeeper:
        condition: service_healthy

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Map to a different host port to avoid conflict
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      DATABASE_URI: ${DATABASE_URI}
      REDIS_URL: ${REDIS_URL}
      KAFKA_BROKER: ${KAFKA_BROKER}
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: run.py
      FLASK_ENV: ${FLASK_ENV}

  logging_service:
    build:
      context: ./logging_service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./logging_service/app
        target: /www/app
    depends_on:
      zookeeper:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      FLASK_DEBUG: 1
      FLASK_APP: ./run.py
      DATABASE_URL: ${DATABASE_URI}

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.6
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      
volumes:
  postgres_data:
